import type { CSSProperties } from 'react'

export type TemplateSlotSpec = {
  baseFontPx: number
  minFontPx: number
  lineHeight: number
  maxLines: number
  whiteSpace?: CSSProperties['whiteSpace']
  textAlign?: CSSProperties['textAlign']
  textTransform?: CSSProperties['textTransform']
  overflowWrap?: CSSProperties['overflowWrap']
  wordBreak?: CSSProperties['wordBreak']
  letterSpacing?: CSSProperties['letterSpacing']
}

const slot = (spec: TemplateSlotSpec): TemplateSlotSpec => spec

export const TEMPLATE_SLOT_SPECS = {
  templateHeaderTitle: slot({
    baseFontPx: 40,
    minFontPx: 18,
    lineHeight: 0.98,
    maxLines: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
  }),
  templateHeaderSubtitle: slot({
    baseFontPx: 11,
    minFontPx: 9,
    lineHeight: 1.08,
    maxLines: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: '0.16em',
  }),
  templateHeaderMeta: slot({
    baseFontPx: 11,
    minFontPx: 9,
    lineHeight: 1.08,
    maxLines: 1,
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '0.16em',
    whiteSpace: 'nowrap',
  }),
  matchupSupplement: slot({
    baseFontPx: 18,
    minFontPx: 10,
    lineHeight: 1.05,
    maxLines: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
  }),
  fighterBannerName: slot({
    baseFontPx: 28,
    minFontPx: 16,
    lineHeight: 1,
    maxLines: 1,
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
    textAlign: 'left',
  }),
  fighterBannerNameLarge: slot({
    baseFontPx: 58,
    minFontPx: 22,
    lineHeight: 1,
    maxLines: 1,
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
    textAlign: 'left',
  }),
  heroName: slot({
    baseFontPx: 24,
    minFontPx: 14,
    lineHeight: 1,
    maxLines: 1,
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
    textAlign: 'left',
  }),
  heroSubtitle: slot({
    baseFontPx: 14,
    minFontPx: 10,
    lineHeight: 1.1,
    maxLines: 2,
    textAlign: 'left',
  }),
  heroLabel: slot({
    baseFontPx: 10,
    minFontPx: 8,
    lineHeight: 1.05,
    maxLines: 1,
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '0.16em',
    whiteSpace: 'nowrap',
  }),
  quoteBody: slot({
    baseFontPx: 18,
    minFontPx: 11,
    lineHeight: 1.15,
    maxLines: 3,
    textAlign: 'left',
  }),
  factTitle: slot({
    baseFontPx: 10,
    minFontPx: 8,
    lineHeight: 1.05,
    maxLines: 1,
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
    textAlign: 'left',
    letterSpacing: '0.2em',
  }),
  factBody: slot({
    baseFontPx: 14,
    minFontPx: 10,
    lineHeight: 1.15,
    maxLines: 2,
    textAlign: 'left',
  }),
  imageCaption: slot({
    baseFontPx: 11,
    minFontPx: 8,
    lineHeight: 1.1,
    maxLines: 2,
    textAlign: 'left',
  }),
  imageCaptionCentered: slot({
    baseFontPx: 11,
    minFontPx: 8,
    lineHeight: 1.1,
    maxLines: 2,
    textAlign: 'center',
  }),
  sectionLabel: slot({
    baseFontPx: 11,
    minFontPx: 8,
    lineHeight: 1,
    maxLines: 1,
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    whiteSpace: 'nowrap',
  }),
  summaryWinner: slot({
    baseFontPx: 42,
    minFontPx: 18,
    lineHeight: 1.06,
    maxLines: 2,
    textAlign: 'left',
  }),
  summaryLine: slot({
    baseFontPx: 15,
    minFontPx: 10,
    lineHeight: 1.16,
    maxLines: 3,
    textAlign: 'left',
  }),
  scoreLabel: slot({
    baseFontPx: 12,
    minFontPx: 8,
    lineHeight: 1,
    maxLines: 1,
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '0.16em',
    whiteSpace: 'nowrap',
  }),
  scoreValue: slot({
    baseFontPx: 28,
    minFontPx: 14,
    lineHeight: 1,
    maxLines: 1,
    textAlign: 'left',
  }),
  directVerdictWinner: slot({
    baseFontPx: 46,
    minFontPx: 22,
    lineHeight: 0.98,
    maxLines: 2,
    textAlign: 'left',
    textTransform: 'uppercase',
  }),
  directVerdictSubline: slot({
    baseFontPx: 18,
    minFontPx: 11,
    lineHeight: 1.16,
    maxLines: 2,
    textAlign: 'left',
  }),
  directVerdictCard: slot({
    baseFontPx: 16,
    minFontPx: 10,
    lineHeight: 1.15,
    maxLines: 3,
    textAlign: 'left',
  }),
  battleDynamicsPhase: slot({
    baseFontPx: 16,
    minFontPx: 10,
    lineHeight: 1.14,
    maxLines: 4,
    textAlign: 'left',
  }),
  battleDynamicsAnalysis: slot({
    baseFontPx: 20,
    minFontPx: 12,
    lineHeight: 1.14,
    maxLines: 2,
    textAlign: 'center',
  }),
  tacticalBoardTile: slot({
    baseFontPx: 18,
    minFontPx: 10,
    lineHeight: 1.05,
    maxLines: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
  }),
  interpretationBadge: slot({
    baseFontPx: 46,
    minFontPx: 18,
    lineHeight: 0.94,
    maxLines: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
  }),
  interpretationBarLabel: slot({
    baseFontPx: 20,
    minFontPx: 11,
    lineHeight: 1,
    maxLines: 1,
    whiteSpace: 'nowrap',
    textAlign: 'left',
    textTransform: 'uppercase',
  }),
  interpretationBullet: slot({
    baseFontPx: 20,
    minFontPx: 12,
    lineHeight: 1.14,
    maxLines: 2,
    textAlign: 'left',
  }),
  interpretationQuote: slot({
    baseFontPx: 18,
    minFontPx: 11,
    lineHeight: 1.14,
    maxLines: 2,
    textAlign: 'center',
  }),
  statTrapHeadline: slot({
    baseFontPx: 24,
    minFontPx: 12,
    lineHeight: 1,
    maxLines: 1,
    textAlign: 'center',
    textTransform: 'uppercase',
  }),
  statTrapExample: slot({
    baseFontPx: 20,
    minFontPx: 11,
    lineHeight: 1.08,
    maxLines: 7,
    whiteSpace: 'pre-line',
    textAlign: 'left',
  }),
  statTrapQuestion: slot({
    baseFontPx: 18,
    minFontPx: 11,
    lineHeight: 1.1,
    maxLines: 3,
    textAlign: 'left',
  }),
  xFactorSupplement: slot({
    baseFontPx: 18,
    minFontPx: 10,
    lineHeight: 1.05,
    maxLines: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
  }),
  xFactorInsightTitle: slot({
    baseFontPx: 16,
    minFontPx: 10,
    lineHeight: 1,
    maxLines: 1,
    textTransform: 'uppercase',
    textAlign: 'left',
  }),
  xFactorInsightBody: slot({
    baseFontPx: 15,
    minFontPx: 10,
    lineHeight: 1.12,
    maxLines: 5,
    textAlign: 'left',
  }),
  parameterAdvantageLabel: slot({
    baseFontPx: 12,
    minFontPx: 8,
    lineHeight: 1,
    maxLines: 1,
    textTransform: 'uppercase',
    textAlign: 'left',
  }),
  parameterAdvantageValue: slot({
    baseFontPx: 16,
    minFontPx: 10,
    lineHeight: 1.08,
    maxLines: 2,
    textAlign: 'left',
  }),
  parameterPanelHeader: slot({
    baseFontPx: 12,
    minFontPx: 8,
    lineHeight: 1.04,
    maxLines: 2,
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '0.16em',
  }),
  parameterAdvantageList: slot({
    baseFontPx: 13,
    minFontPx: 8,
    lineHeight: 1.1,
    maxLines: 10,
    textAlign: 'left',
    whiteSpace: 'pre-line',
  }),
  parameterFavoriteStamp: slot({
    baseFontPx: 15,
    minFontPx: 10,
    lineHeight: 1.04,
    maxLines: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
  }),
  methodologyItem: slot({
    baseFontPx: 18,
    minFontPx: 10,
    lineHeight: 1.12,
    maxLines: 2,
    textAlign: 'left',
  }),
  methodologyClosing: slot({
    baseFontPx: 42,
    minFontPx: 18,
    lineHeight: 1.02,
    maxLines: 2,
    textAlign: 'left',
  }),
  verdictMatrixHeader: slot({
    baseFontPx: 38,
    minFontPx: 12,
    lineHeight: 1,
    maxLines: 1,
    textAlign: 'center',
    textTransform: 'uppercase',
  }),
  verdictMatrixRowHeader: slot({
    baseFontPx: 16,
    minFontPx: 10,
    lineHeight: 1,
    maxLines: 1,
    whiteSpace: 'nowrap',
    textAlign: 'center',
    textTransform: 'uppercase',
  }),
  verdictMatrixLead: slot({
    baseFontPx: 24,
    minFontPx: 12,
    lineHeight: 1.08,
    maxLines: 2,
    textAlign: 'left',
    textTransform: 'uppercase',
  }),
  verdictMatrixBody: slot({
    baseFontPx: 19,
    minFontPx: 11,
    lineHeight: 1.08,
    maxLines: 4,
    textAlign: 'left',
  }),
  phaseTitle: slot({
    baseFontPx: 20,
    minFontPx: 11,
    lineHeight: 1.08,
    maxLines: 2,
    textAlign: 'left',
  }),
  phaseEvent: slot({
    baseFontPx: 13,
    minFontPx: 9,
    lineHeight: 1.12,
    maxLines: 3,
    textAlign: 'left',
  }),
  phaseBranch: slot({
    baseFontPx: 12,
    minFontPx: 9,
    lineHeight: 1.12,
    maxLines: 4,
    textAlign: 'left',
  }),
  phaseScenarioLabel: slot({
    baseFontPx: 10,
    minFontPx: 8,
    lineHeight: 1,
    maxLines: 2,
    textAlign: 'right',
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
  }),
  endCondition: slot({
    baseFontPx: 18,
    minFontPx: 11,
    lineHeight: 1.08,
    maxLines: 2,
    textAlign: 'center',
  }),
  fightCardName: slot({
    baseFontPx: 96,
    minFontPx: 42,
    lineHeight: 0.78,
    maxLines: 1,
    textAlign: 'center',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  }),
} satisfies Record<string, TemplateSlotSpec>

export type TemplateSlotSpecId = keyof typeof TEMPLATE_SLOT_SPECS
